### ISSUE TITLE
In windows grok_exporter metrics not getting updated to browser.

### ISSUE THREAD

**Issue by arunsraga** [fstab/grok_exporter#17] opened 2017-09-12 10:16 UTC
I have tried to access metrics from the apache logs using grok_exporter in windows 10 environment. I getting following issuses/errors.

1) "Error reading log lines: failed to watch C:\Apache24\logs\access_log: read error: read C:\Apache24\logs\access_log: The process cannot access the file because another process has locked a portion of the file" After sometime.

2) Hitting  some load to apache web server, But "http://localhost:9144/metrics" i am getting old metrics not updated metrics(i have tried by making readfile true/false both options).
i have took "exe file" from this [link](https://github.com/fstab/grok_exporter/releases/download/v0.2.0/grok_exporter-0.2.0.windows-amd64.zip).
3) When i am running "tail -f /var/log/access_log" in terminal and grok_exporter in other terminal real time metrics getting in browser, But after some time  ending with above mentioned error(1).

**Comment by fstab** [comment] 2017-09-13 08:15
Hello Arunsraga, thanks for the issue. The reason for the errors seems to be that Windows doesn't allow two programs to keep an open file handle for the logfile at the same time. grok_exporter already minimized the time it keeps the file open, but maybe it was not enough.

I pushed some code that should fix the problem. Instead of giving up directly when `os.Open()` fails, grok_exporter now tries a few times after a backoff interval (giving the logger time to write its line and close the file). This should fix timing issues when a logger writes to a file and and grok_exporter reads the file at the same time.

I usually run grok_exporter on Linux, so I would be happy if you could test if the fix works for Windows. I did a test on a Windows VM, but I don't have any long-running Windows set-up. You could either build the current `master` from source, or download a snapshot from here: https://drive.google.com/file/d/0B-X-pcUWzFNpbjg1aHFUNFJmM28/view?usp=sharing

**Comment by arunsraga** [comment] 2017-09-13 08:50
Hi Fsatb,  Thank you for your reply.  I Have checked with new version Executable file which you are shared. I am still facing issue of getting older metrics in browser even though apache server getting new request.

On running commands like "ls -la" in log file existing directory or on "tail -f access.log". I will get real time metrics in browser, It seems access log file tailer is not working.

**Comment by fstab** [comment] 2017-09-13 12:43
I cannot really re-produce the error. I downloaded a fresh Windows 10 VirtualBox image from Microsoft and created a BAT script that writes log files like this:

```bat
@echo off
for /l %%x in (1, 1, 100) do (
    echo test log line %%x >> logfile.log
    timeout 1 > nul
)
```

Then I ran `grok_exporter` with the following config:

```
global:
    config_version: 2
input:
    type: file
    path: .\logfile.log
    readall: true
grok:
    patterns_dir: ./patterns
metrics:
    - type: counter
      name: log_lines_total
      help: Total number of lines.
      match: 'test log line %{INT}'
server:
    host: localhost
    port: 9144
```

As expected, `grok_exporter` increments the `log_lines_total` metric every second.

Do you see any reason why my test does not reproduce your error?

**Comment by arunsraga** [comment] 2017-09-14 07:39
I have tried above code snippet. It's working properly. i have not found any issues.

When i try for apache web server logs i get issue, I have tried following cases.
  1) I moved  apache log file("access.log") from "C" directory  to grok_exporter working directory (local to working directory), to check any permission or path(C: directory) issue, It's not worked.

  2)  I was using apache_exporter (https://github.com/bblok11/apache_exporter) along with grok_exporter, I suspected apache_exporter and stopped, still same issue.

Is it required to mention anything in  "config.yml" file for tailing.
Following is my "config.yml" snippet,

////////////////////////////////////////

global:
    config_version: 2
input:
    type: file
    path: \Apache24\logs\access.log
    readall: false #Read from the beginning of the file? False means we start at the end of the file and read only new lines.
grok:
    patterns_dir: ./patterns
metrics:
    - type: counter
      name: path
      help: Total number of methods.
      match: '%{IP:client_ip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:apache_timestamp}\] \"%{WORD:method} /%{NOTSPACE:request_page} HTTP/%{NUMBER:http_version}\" %{NUMBER:server_response}'
      labels:
          uri_path: '{{.request_page}}'
    - type: counter
      name: status
      help: status.
      match: '%{IP:client_ip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:apache_timestamp}\] \"%{WORD:method} /%{NOTSPACE:request_page} HTTP/%{NUMBER:http_version}\" %{NUMBER:server_response}'
      labels:
          status: '{{.server_response}}'
server:
    host: localhost
    port: 9144

**Comment by fstab** [comment] 2017-09-14 20:59
I installed Apache on my Windows 10 VM, and I can reproduce the error now. I am not sure why this happens. I will summarize my findings here:

I think you can track down the behaviour with a regular `cmd` window:

1. `cd C:\Apache24\logs\`, then run `dir`. This will show you (among other things) the `access.log` file with the current file size in bytes and the last modification time.
2. Send a few requests to the Apache server and type `dir` again. Surprisingly, the modification time and the file size in bytes is not changed, even though Apache should have written some lines to `access.log`.
3. View the contents of the file using `type access.log`. It turns out, the new log lines have actually been written.
4. Run `dir` again: Now the file size in bytes and the last modification time is updated, even though the `type` command did not modify the size of the file.

The `grok_exporter` listens to changes of the file size. If the file size is not changed, `grok_exporter` will not get new log lines. It seems that with Apache logs, the file size is updated when the log file is accessed, not when new log lines are written. This is the reason why you see an update in `grok_exporter` metrics as soon as you open the file in Notepad++, but not when Apache writes log lines.

However, I didn't find out yet how Apache writes log lines without modifying the file size on the file system. I had a quick look into Apache's source code, but there are some levels of indirection (like the Apache Portable Runtime (APR)), so it's not obvious how exactly Apache writes logs on Windows.

I will try to figure this out and comment here if I find something.

**Comment by arunsraga** [comment] 2017-09-15 04:40
Thank you for your time and support.

**Comment by fstab** [comment] 2017-09-16 19:10
I figured out what's going on. The error occurs when the following two things come together:
* The application does not close the log file after each log message, but keeps the log file open (Apache is one of the few applications keeping log files open).
* NTFS file system (which is the default in Windows 10)

`grok_exporter` uses the Windows system call `ReadDirectoryChangesW` to be notified when the size of the log file changes. That system call gets the file size from the directory metadata (like the `dir` command). As described [here](https://blogs.msdn.microsoft.com/oldnewthing/20111226-00/?p=8813), Windows updates the directory metadata only when the file is closed. As Apache keeps the file open, `grok_exporter` does not get the update. If you open and close the file in another application (like Notepad++), the directory metadata is updated and the notification is triggered.

I think the best way to fix this is to implement a polling loop in `grok_exporter` that can be used as a fallback if this problem occurs. A polling loop repeatedly checks the logfile every few seconds, and does not rely on `ReadDirectoryChangesW` notifications. I will implement this in the next couple of days.

There are two workarounds you could experiment with in the meantime:
* Use the pipe command in Apache's [mod_log_config](http://httpd.apache.org/docs/current/mod/mod_log_config.html). The pipe character in the `CustomLog` directive lets you specify a program to receive the log information on its standard input. This could be some small program or script that opens and closes the logfile for each log message. It would be great to pipe log data directly to `grok_exporter` (configuring `grok_exporter` to use the `stdin` as input), but unfortunately Apache seems to start multiple instances of the pipe command. This fails with `grok_exporter`, because all instances would try to open TCP port 9144 for exposing the metrics.
* As you say `tail -f` works, you could run `tail -f C:\Apache24\logs\access.log | .\grok_exporter -config config.yml` and configure `grok_exporter` to read from stdin.

Apart from that you wrote that you saw an error message '_the process cannot access the file because another process has locked a portion of the file_'. This is another bug that has nothing to do with above. I forgot to set the `FILE_SHARE_READ` flag when opening the log file. I will fix this when I implement the poll loop.
Thanks for testing `grok_exporter` on Windows, seems that not a lot of people tried this combination before :)

**Comment by fstab** [comment] 2017-09-22 18:40
I published [release 0.2.2](https://github.com/fstab/grok_exporter/releases/tag/v0.2.2) with a workaround for your problem. Use the new `poll_interval_seconds` option in the `input` section to disable file system notifications and poll the log file repeatedly:

```yaml
input:
    type: file
    path: \Apache24\logs\access.log
    poll_interval_seconds: 5
```

This will make `grok_exporter` check `access.log` every 5 seconds, which should be a workaround for the NTFS + Apache problem.

**Comment by arunsraga** [comment] 2017-09-25 04:53
Thank You..

**Comment by arunsraga** [comment] 2017-09-26 04:53
Hi Fabian Stäber, 
    I am still getting following error.
      "**Error reading log lines: failed to watch C:\Apache24\logs\access.log: read error: read C:\Apache24\logs\access.log: The process cannot access the file because another process has locked a portion of the file**".

**Comment by fstab** [comment] 2017-09-26 08:02
Ok, then we need to get back to finding the error. My understanding is that Apache and `grok_exporter` should be able to open the log file concurrently, as they both use the `FILE_SHARE_READ` and `FILE_SHARE_WRITE` attributes with the Windows `CreateFileW` system call (as of `grok_exporter` version 0.2.2).

I wrote a small BAT script generating one HTTP request per second, so that Apache writes one line per second to `access.log`. The batch script uses [curl for Windows](https://curl.haxx.se/download.html):

```bat
@echo off
for /l %%x in (1, 1, 10000) do (
    .\curl-7.55.1\curl.exe http://localhost
    timeout 1 > nul
)
```

Then I configured `grok_exporter` with a `poll_interval_seconds: 2`, and let it run for a while. It worked without any problems, the metrics for the log line count increased every second as expected.

Maybe the problem is not caused by Apache or `grok_exporter`. Is there any other program running that might have locked `access.log`? Maybe a text editor or a virus scanner? Could you make sure no other program is locking `access.log`, add `access.log` to the exclusion list of your virus scanner, and try again?

**Comment by arunsraga** [comment] 2017-09-26 11:15
I have cross checked the following test cases. 
  1) I have stopped antivirus scan for apache "log" directory. It not worked. 
   2) No other exporter or process accessing the "access.log" file.
   3) The  **"access.log"** file size is 350 MB, deleted and restarted the apache server this also not worked.
   4) I am generating a load by using this nodejs [module](https://www.npmjs.com/package/loadtest).
      i) if request  count is minimal i.e     
          **"loadtest -c 2 --rps 20 http://192.168.2.128/test/login"**
       

>           **This case working properly and no issues.**


     ii) If request is as follows
         **"loadtest -c 100 --rps 500 http://192.168.2.128/test/login "**
     This case getting failed by specified error by terminating grok_exporter.

**Comment by fstab** [comment] 2017-10-01 13:25
I cannot reproduce the error. I installed the nodejs loadtest module in my Windows 10 VM. I used the options `-c 100 --rps 500` as you said above. I kept it running until 500,000 log lines were produced in `access.log`, but I did not see any error in `grok_exporter` reading `access.log` or in Apache writing `access.log`. The only errors I see is that loadtest needs to drop some requests because nodejs reaches 100% CPU usage.

Could you please double check that you used `grok_exporter` 0.2.2 with the `poll_interval_seconds` config? If the error persists on your side, I will try to set up an AppVeyor environment to reproduce it, because without a reproducible error it's hard to track this down.

**Comment by fstab** [comment] 2017-11-14 21:47
Closing the issue. If the error persists on your side feel free to re-open it. Then we need to find a way to reproduce it on my machine :)

**Closed by fstab** 2017-11-14 21:47 UTC
