### ISSUE TITLE
multiple match filters

### ISSUE THREAD

**Issue by VinistoisR** [fstab/grok_exporter#99] opened 2020-05-03 00:47 UTC
I have log lines like this 

```
May  3 00:41:07 172.16.50.150 /var/log/pald.log[821] ﻿MALONE UPS 1: Output Current = 5.00
May  3 00:41:09 172.16.50.150 /var/log/pald.log[821] ﻿MALONE UPS 1: Output Current = 4.00
May  3 00:41:17 172.16.50.150 /var/log/pald.log[839] ﻿MALONE UPS 2: Battery Minutes Remaining = 32
May  3 00:41:24 172.16.50.150 /var/log/pald.log[821] ﻿MALONE UPS 1: Input Voltage = 120.1
May  3 00:41:25 172.16.50.150 /var/log/pald.log[839] ﻿MALONE UPS 2: Input Voltage = 119.0
May  3 00:41:27 172.16.50.150 /var/log/pald.log[821] ﻿MALONE UPS 1: Battery Voltage = 54.3
May  3 00:41:36 172.16.50.150 /var/log/pald.log[839] ﻿MALONE UPS 2: Battery Minutes Remaining = 33
```

so I matched them up with this filter
```
match: '%{MONTH:month}%{SPACE}%{MONTHDAY:day}%{SPACE}%{TIME:time}%{SPACE}%{USER}%{SPACE}%{PATH}%{NOTSPACE}%{NUMBER}%{NOTSPACE}%{SPACE}%{NOTSPACE:location}%{SPACE}%{NOTSPACE:asset}%{SPACE}%{INT:id}%{NOTSPACE}%{SPACE}(?<measurement>%{WORD}%{SPACE}%{WORD})%{SPACE}%{NOTSPACE}%{SPACE}%{NUMBER:val}'
```
This works great, except it fails to catch the message that has a third word in the value label.  So I made another one that catches it:
```
match: '%{MONTH:month}%{SPACE}%{MONTHDAY:day}%{SPACE}%{TIME:time}%{SPACE}%{USER}%{SPACE}%{PATH}%{NOTSPACE}%{NUMBER}%{NOTSPACE}%{SPACE}%{NOTSPACE:location}%{SPACE}%{NOTSPACE:asset}%{SPACE}%{INT:id}%{NOTSPACE}%{SPACE}(?<measurement>%{WORD}%{SPACE}%{WORD}%{SPACE}%{WORD})%{SPACE}%{NOTSPACE}%{SPACE}%{NUMBER:val}'
```
but I couldn't figure out how to run them both at the same time. 

So, I just doubled up on the docker containers instead, and that way I end up with my exact desired result:

![image](https://user-images.githubusercontent.com/36953653/80895725-d421e780-8c9c-11ea-8857-abf422d76eba.png)

But there must be a way to get both of those into the same line?

**Comment by fstab** [comment] 2020-05-03 21:12
You are pretty close. A pattern to match an arbitrary number of words looks like this:
```
(%{WORD}%{SPACE}?)+
```
That means: A word, followed by an optional space, and the whole thing might repeat multiple times.

Instead of copying this directly into your match, you could define it as a pattern named `WORDS` and use it in your match like this:
```yaml
grok_patterns:
- 'WORDS (%{WORD}%{SPACE}?)+'
metrics:
- type: gauge
  name: gauge_1
  help: example gauge 1
  match: '%{MONTH:month}%{SPACE}%{MONTHDAY:day}%{SPACE}%{TIME:time}%{SPACE}%{USER}%{SPACE}%{PATH}%{NOTSPACE}%{NUMBER}%{NOTSPACE}%{SPACE}%{NOTSPACE:location}%{SPACE}%{NOTSPACE:asset}%{SPACE}%{INT:id}%{NOTSPACE}%{SPACE}%{WORDS:measurement}%{SPACE}%{NOTSPACE}%{SPACE}%{NUMBER:val}'
  labels:
    measurement: '{{.measurement}}'
  value: '{{.val}}'
```

However, your match is a bit long, and you might consider simplifying it. This depends on your loglines and it's hard to tell without knowing what else is in your log, but to give you an example: If you know the measurement starts after a `:`, and the separater between the measurement and the value is a ` = `, and you don't care about the rest, you could write the match like this:
```yaml
- type: gauge
  name: gauge_2
  help: example guage 2
  match: ': %{WORDS:measurement} = %{NUMBER:val}'
  labels:
    measurement: '{{.measurement}}'
  value: '{{.val}}'
```

**Comment by VinistoisR** [comment] 2020-05-03 21:43
Ah that's a great clue, thanks for taking the time to answer.  Is there a resource that covers the use of the ? And the + in these filters? 
In your example, you start with a colon, does it just skip everything until it finds one? 

If one Grok filter is more elegant than the other but gives the same result, is there an efficiency difference? 

I didn't know how to "get rid" of the number contained in square brackets. I'm not particularly interested in it, so I just did %{NOTSPACE}%{NUMBER}%{NOTSPACE}.  I bet there's an easier way...

**Comment by fstab** [comment] 2020-05-04 19:28
The matches are just regular expressions, so if you want to learn more about `?` and `+` you can read any resource about regular expressions.
* `?` means _zero or one_ occurrence
* `+` means _one or more_ occurrences

As regular expressions tend to be hard to read, we introduced Grok patterns like `%{WORD}`, which are placeholders for regular expression snippets. For example, `WORD` is the same as `\b\w+\b` as defined [here](https://github.com/logstash-plugins/logstash-patterns-core/blob/6d25c13c15f98843513f7cdc07f0fb41fbd404ef/patterns/grok-patterns#L14), and `%{SPACE}` is the same as `\s*` as defined [here](https://github.com/logstash-plugins/logstash-patterns-core/blob/6d25c13c15f98843513f7cdc07f0fb41fbd404ef/patterns/grok-patterns#L16). As we defined `%{WORDS}` as `(%{WORD}%{SPACE}?)+` it is the same as the regular expression `((?:\b\w+\b)(?:\s*)?)+`. As you can see, the regular expression is much harder to read, so it makes sense to define little snippets like `%{WORD}` or `%{SPACE}` to improve readability.

> you start with a colon, does it just skip everything until it finds one?

yes

> is there an efficiency difference?

Yes, you can easily define regular expressions that take very long to evaluate, but the length of the regular expression is not an indicator for that. You can have long regular expressions that are efficient, and you can have short ones that are inefficient. If you experience performance problems, check `grok_exporter`'s built-in metric `grok_exporter_lines_processing_time_microseconds_total` to learn if this is caused by an inefficient regular expression, as described [here](https://github.com/fstab/grok_exporter/blob/master/BUILTIN.md).

> how to "get rid" of the number contained in square brackets

The easiest way to just "get rid" of something is to use `.*`, which matches an arbitrary long sequence of arbitrary characters. If you specifically want to match a `[` or `]`, you need to escape it as `\[` or `\]` because `[` and `]` are special characters in regular expressions. So you could write `\[%{NUMBER}\]`.

**Comment by fstab** [comment] 2020-05-11 19:28
Closing this one. Feel free to open a new issue if there are more questions.

**Closed by fstab** 2020-05-11 19:28 UTC
